genres = [
    "pop",
    "rap",
    "pop rap",
    "trap",
    "rock",
    "modern rock",
    "alternative rock",
    "modern country rock",
    "folk rock",
    "modern alternative rock",
    "country rock",
    "grunge",
    "edm",
    "country",
    "contemporary country",
    "modern country rock",
    "modern country pop",
    "red dirt",
    "indie",
    "metal",
    "jazz",
    "folk",
    "electronic",
    "house",
    "hip-hop",
    "punk",
    "blues",
    "classical"
]