WIKIPEDIA_MAX_REQUESTS_PER_MINUTE = 200
WIKIPEDIA_REQUEST_INTERVAL_SECONDS = 60.0 / WIKIPEDIA_MAX_REQUESTS_PER_MINUTE

# Set to False when running small test extractions to skip throttling
THROTTLE_WIKIPEDIA_REQUESTS = True
